routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Frontend\{
    HomepageController,
};
use App\Http\Controllers\Backend\{
    DashboardController,
    UserController,
    ConfigsController,
    PagesController,
    CustomersController,
    ServicesController,
    PortfoliosController,
    TeamsController,
    LinkPixsController,
    CountersController,
};

// *****************************************************

// Routes Site - Frontend
Route::get('/', [HomepageController::class, 'index']);
Route::get('/sobre', [HomepageController::class, 'about']);
Route::get('/servicos', [HomepageController::class, 'services']);
Route::get('/servico/{slugService}', [HomepageController::class, 'showService']);
Route::get('/portfolio', [HomepageController::class, 'portfolio']);
Route::get('/portfolio/{slugPortfolio}', [HomepageController::class, 'showPortfolio']);
Route::get('/portfolio/video/{id}', [HomepageController::class, 'portfolioVideos']);
Route::get('/portfolio/photos/{id}', [HomepageController::class, 'portfolioPhotos']);

Route::get('/clientes', [HomepageController::class, 'clientes']);
Route::get('/contato', [HomepageController::class, 'contato']);
Route::post('/contato-sendmail', [HomepageController::class, 'sendMail']);

Route::get('/redirect/{slug}', [HomepageController::class, 'showLinkPix']);

// *****************************************************

// Routes Admin - Middleware Auth
Auth::routes();

Route::prefix('dashboard')->middleware('auth')->group(function () {
    // Home
    Route::resource('/', DashboardController::class);

    // Resources
    Route::group(['prefix' => 'laravel-filemanager'], function () {
        \UniSharp\LaravelFilemanager\Lfm::routes();
    });

    // Usuários Admin
    Route::resource('users', UserController::class);
    Route::get('users/showsearch', [UserController::class, 'showsearch'])->name('users.showsearch');
    Route::post('users/search', [UserController::class, 'search'])->name('users.search');
    
    // Configurações Geral
    Route::get('configs', [ConfigsController::class, 'index'])->name('configs');
    Route::put('configs/{id}', [ConfigsController::class, 'update'])->name('configs.update');

    // Counter
    Route::resource('counter', CountersController::class);
    Route::put('counter/{id}', [CountersController::class, 'update'])->name('counter.update');
    
    // Paginas de Informações
    Route::resource('pages', PagesController::class);
    Route::get('pages/{slugPage}', [PagesController::class, 'show']);
    
    // Clientes
    Route::resource('customers', CustomersController::class);
    Route::post('customers/change/{id}/{new_order}', [CustomersController::class, 'change_position']);
    
    Route::resource('link_pixs', LinkPixsController::class);
    
    // Serviços
    Route::resource('services', ServicesController::class);
    Route::get('services/{slugService}', [ServicesController::class, 'show']);
    
    // Porfolio
    Route::resource('portfolios', PortfoliosController::class);
    Route::get('portfolios/{slugPortfolio}', [PortfoliosController::class, 'show']);
    Route::delete('portfolio-image/{portfolioID}/{imageID}', [PortfoliosController::class, 'destroyImage']);
    Route::post('portfolios/change/{id}/{new_order}', [PortfoliosController::class, 'change_position']);

    // Time
    Route::resource('teams', TeamsController::class);

   
});

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    use HasFactory;

    protected $fillable = [
        'meta_title',
        'meta_description',
        'meta_keywords',
        'image',
        'content',
        'slug',
        'status',
    ];

}

app/Http/Controllers/Backend/ConfigsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\Config;

class ConfigsController extends Controller
{
    /* Variables globais */
    public $folder = 'backend.configs.'; // required ponto final

    public function index()
    {
        $config = Config::first();
        return view($this->folder . 'index', [
            'config' => $config
        ]);
    }

    public function update(Request $request, $id)
    {
        $model = new Config;
        $model = $model::find($id);

        $result = $request->all();

        $rules = [
            'meta_title'        => 'required',
            'meta_description'  => 'max:255',
            'name_site'         => 'required',
            'proprietary'       => 'required',
            'email_admin'       => 'required|email',
            'logo'              => 'nullable',
        ];

        $messages = [
            'meta_title.required' => 'título é obrigatório',
            'meta_description.max' => 'máximo de 255 caracteres',
            'name_site.required' => 'nome do site é obrigatório',
            'proprietary.required' => 'proprietário é obrigatório',
            'email_admin.required' => 'e-mail é obrigatório',
            'logo.required' => 'logo é obrigatório',
        ];

        $validator = Validator::make($result, $rules, $messages);

        if ($validator->fails()) {
            return response()->json($validator->errors()->first(), 422);
        }

        $model->meta_title = $result['meta_title'];
        $model->meta_description = $result['meta_description'];
        $model->meta_keywords = $result['meta_keywords'];
        $model->name_site = $result['name_site'];
        $model->proprietary = $result['proprietary'];
        $model->address = $result['address'];
        $model->cnpj = $result['cnpj'];
        $model->email_admin = $result['email_admin'];
        $model->telephone = $result['telephone'];
        $model->cellphone = $result['cellphone'];
        $model->hour_open = $result['hour_open'];
        $model->twitter = $result['twitter'];
        $model->facebook = $result['facebook'];
        $model->instagram = $result['instagram'];
        $model->whatsapp = $result['whatsapp'];
        if ($result['logo']) {
            $format_url_logo = str_replace(env('APP_URL'), '', $result['logo']);
            $model->logo = $format_url_logo;
        }

        try {
            $model->save();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json('Configurações alteradas com sucesso', 200);
    }
}

app/Http/Controllers/Backend/CountersController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\Counter;

class CountersController extends Controller
{
    /* Variables globais */
    public $folder = 'backend.counters.'; // required ponto final

    public function index()
    {
        $counter = Counter::first();
        return view($this->folder . 'index', [
            'counter' => $counter
        ]);
    }

    public function update(Request $request, $id)
    {
        $model = new Counter;
        $model = $model::find($id);

        $result = $request->all();

        $rules = [
            'title_1'        => 'nullable',
            'number_1'       => 'nullable',
            'title_2'        => 'nullable',
            'number_2'       => 'nullable',
            'title_3'        => 'nullable',
            'number_3'       => 'nullable',
            'title_4'        => 'nullable',
            'number_4'       => 'nullable',
        ];

        $messages = [
            'title_1.required' => 'título #1 é obrigatório',
            'number_1.required' => 'número #1 é obrigatório',
            'title_2.required' => 'título #2 é obrigatório',
            'number_2.required' => 'número #2 é obrigatório',
            'title_3.required' => 'título #3 é obrigatório',
            'number_3.required' => 'número #3 é obrigatório',
            'title_4.required' => 'título #4 é obrigatório',
            'number_4.required' => 'número #4 é obrigatório',
        ];

        $validator = Validator::make($result, $rules, $messages);

        if ($validator->fails()) {
            return response()->json($validator->errors()->first(), 422);
        }

        $model->title_1 = $result['title_1'];
        $model->number_1 = $result['number_1'];
        $model->title_2 = $result['title_2'];
        $model->number_2 = $result['number_2'];
        $model->title_3 = $result['title_3'];
        $model->number_3 = $result['number_3'];
        $model->title_4 = $result['title_4'];
        $model->number_4 = $result['number_4'];
        $model->time = $result['time'];

        try {
            $model->save();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json('Contador alterado com sucesso', 200);
    }
}

app/Http/Controllers/Backend/CustomersController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use App\Models\Customer;

class CustomersController extends Controller
{
    /* Variables globais */
    public $folder = 'backend.customers.';

    /**
     * Display a listing of the resource.
     * // INDEX
     */
    public function index(Request $request)
    {
        $itensPage = $request->input('itensPage') ? $request->input('itensPage') : '5';

        $customers = Customer::orderBy(\DB::raw('-`sort_order`'), 'desc')->paginate($itensPage);

        return view($this->folder . 'index', [
            'customers' => $customers,
            'itensPage' => $itensPage,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     * // CREATE
     */
    public function create()
    {
        return view($this->folder . 'form');
    }

    /**
     * Store a newly created resource in storage.
     * // STORE
     */
    public function store(Request $request)
    {
        $model = new Customer;
        $result = $request->all();

        $rules = [
            'meta_title'          => "required",
            'web_link'          => "nullable|min:5",
            'image'               => "required",
            'status'              => "required",
        ];

        $messages = [
            'meta_title.required'       => 'título é obrigatório',
            'web_link.min'       => 'link minimo de 5 caracteres',
            'image.required'            => 'imagem é obrigatório',
            'status.required'           => 'status é obrigatório',
        ];

        $validator = Validator::make($result, $rules, $messages);

        if ($validator->fails()) {
            return response()->json($validator->errors()->first(), 422);
        }

        $model->meta_title = $result['meta_title'];
        $model->web_link = $result['web_link'];
        if($result['image']){
            $format_url_image = str_replace(env('APP_URL'), '', $result['image']);
            $model->image = $format_url_image;
        }
        $model->status = $result['status'];
        $model->sort_order = $result['sort_order'];

        try {
            $model->save();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json('Cliente salvo com sucesso', 200);
    }

    /**
     * Display the specified resource.
     * // SHOW
     */
    public function show($slugCustomer)
    {
        $customer = new Customer;
        $result = $customer->where('slug', $slugCustomer)->first();

        return view($this->folder . 'show', compact('result'));
    }

    /**
     * Show the form for editing the specified resource.
     * // EDIT
     */
    public function edit($id)
    {
        $customer = new Customer;
        $result = $customer->where('id', $id)->first();

        return view($this->folder . 'form', compact('result'));
    }

    /**
     * Update the specified resource in storage.
     * // UPDATE
     */
    public function update(Request $request, $id)
    {
        $model = new Customer;
        $model = $model::find($id);

        $result = $request->all();

        $rules = [
            'meta_title'          => "required",
            'web_link'          => "nullable|min:5",
            'image'               => "nullable",
            'status'              => "required",
        ];

        $messages = [
            'meta_title.required'       => 'título é obrigatório',
            'web_link.min'       => 'link minimo de 5 caracteres',
            'image.required'            => 'imagem é obrigatório',
            'status.required'           => 'status é obrigatório',
        ];

        $validator = Validator::make($result, $rules, $messages);

        if ($validator->fails()) {
            return response()->json($validator->errors()->first(), 422);
        }

        $model->meta_title = $result['meta_title'];
        $model->web_link = $result['web_link'];
        if($result['image']){
            $format_url_image = str_replace(env('APP_URL'), '', $result['image']);
            $model->image = $format_url_image;
        }
        $model->status = $result['status'];
        $model->sort_order = $result['sort_order'];

        try {
            $model->save();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json('Cliente alterado com sucesso', 200);
    }

    /**
     * Remove the specified resource from storage.
     * // DESTROY
     */
    public function destroy($id)
    {
        $model = new Customer;

        try {
            $find = $model->find($id);
            $find->delete();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json(true, 200);
    }


    public function change_position(Request $request, $id, $new_order)
    {
        $model = new Customer;
        $model = $model::find($id);

        $result = $request->all();

        $model->sort_order = $result['change_position'];

        try {
            $model->save();
        } catch (\Exception $e) {
            \Log::error($e->getMessage());
            return response()->json($e->getMessage(), 500);
        }

        return response()->json(true, 200);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /* Variables globais */
    public $folder = 'backend.';

    public function index(){
        return view($this->folder.'dashboard');
    }
}

resources/views/backend/services/index.blade.php
@extends('backend.app')

@section('title', 'Serviços')

@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ url('/dashboard') }}"><i class="fa fa-home"></i></a>
        </li>
        <li class="breadcrumb-item active" aria-current="service">@yield('title')</li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12 col-12">
            <div class="box">

                <div class="box-header with-border">
                    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-center">
                        <div>
                            <h4 class="box-title">@yield('title')</h4>
                        </div>
                    </div>
                </div><!-- box-header -->

                <div class="box-body">
                    <!-- conteudo -->
                    <div class="table-responsive">
                        <table id="table-request" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th width="70px">Imagem</th>
                                    <th>Título</th>
                                    <th>Criado</th>
                                    <th>Status</th>
                                    <th width="150px"><i class="fa fa-cogs mr-2"></i> Ações</th>
                                </tr>
                            </thead>
                            <tbody id="table-body">
                                @foreach ($services as $service)
                                    <tr id="row_{{ $service->id }}">
                                        <td>{{ $service->id }}</td>
                                        <td><img src="{{ $service->image }}" alt="{{ $service->meta_title }}"
                                                class="img-thumb"></td>
                                        <td>{{ $service->meta_title }}</td>
                                        <td>{{ \Carbon\Carbon::parse($service->created_at)->format('d/m/y H:i') }}</td>
                                        <td>{{ $service->status }}</td>
                                        <td>
                                            <a href="{{ route('services.show', $service->slug) }}"
                                                class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top"
                                                title="Ver Serviço"><i class="fa fa-eye"></i></a>

                                            <a href="{{ route('services.edit', $service->id) }}"
                                                class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top"
                                                title="Editar Serviço"><i class="fa fa-edit"></i></a>

                                            <a href="javascript:;" data-id="{{ $service->id }}"
                                                class="btn btn-sm btn-danger btn-delete" data-toggle="tooltip"
                                                data-placement="top" title="Deletar Serviço?"><i
                                                    class="fa fa-trash"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <hr class="m-4">
                    <div id="section-pagination"
                        class="d-flex flex-column flex-lg-row justify-content-between align-items-center">
                        <div class="mt-2 mt-lg-0">
                            <select name="itensPage" id="itensPage" class="form-control" data-toggle="tooltip"
                                data-placement="top" title="Quantidade por Página">
                                <option value="5" {{ $itensPage == '5' ? 'selected' : '' }}>5</option>
                                @for ($i = 10; $i < 50; $i += 10)
                                    <option value="{{ $i }}" {{ $itensPage == $i ? 'selected' : '' }}>
                                        {{ $i }}</option>
                                @endfor
                                <option value="50" {{ $itensPage == '50' ? 'selected' : '' }}>50</option>
                                <option value="100" {{ $itensPage == '100' ? 'selected' : '' }}>100</option>
                            </select>
                        </div>
                        {{ $services->appends(request()->query())->links() }}
                    </div>
                    <!-- conteudo -->
                </div><!-- box-body -->

                <div class="box-footer flexbox">
                    <div class="text-left flex-grow">
                        <a href="{{ route('services.create') }}" class="btn btn-rounded btn-success btn-mobile-float"
                            data-toggle="tooltip" data-placement="top" title="Novo Serviço"><i class="fa fa-plus"></i>
                            <span>Novo Serviço</span></a>
                    </div>
                </div><!-- box-footer -->

            </div><!-- box -->
        </div><!-- cols -->
    </div><!-- row -->
@endsection

@section('includeCSS')
    <!-- Include SweetAlert -->
    <link rel="stylesheet" href="{{ asset('/plugins/sweetalert/sweetalert2.min.css') }}">
@endsection

@section('includeJS')
    <!-- Include SweetAlert -->
    <script src="{{ asset('/plugins/sweetalert/sweetalert2.min.js') }}"></script>
    <script>
        // Change Quantity Pagination
        $('#itensPage').on('change', function() {
            var itensPage = $(this).val();
            var url = '/dashboard/services?itensPage=' + itensPage; // get selected value
            if (url) { // require a URL
                window.location = url; // redirect
            }
            return false;
        });

    </script>
    <script>
        // Button Search
        $(document).on('click', '#btn-search', function(e) {
            e.preventDefault();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': "{{ csrf_token() }}"
                }
            });
            var method = 'POST';
            var url = "{{ url('dashboard/services/search') }}";
            var data = $('#form-search').serialize();

            $.ajax({
                url: url,
                data: data,
                method: method,
                success: function(data) {
                    $('.page-title, .box-title').html('Resultado da Busca')
                    $('#table-body').html('');
                    $('#section-pagination').html('');
                    $('#table-body').html(data);
                },
                error: function(xhr) {
                    if (xhr.status === 422) {
                        Swal.fire({
                            text: xhr.responseJSON,
                            icon: 'info',
                            showClass: {
                                popup: 'animate_animated animate_wobble'
                            }
                        });
                    } else {
                        Swal.fire({
                            text: 'Erro interno, informe ao suporte: ' + xhr.responseJSON,
                            icon: 'error',
                            showClass: {
                                popup: 'animate_animated animate_wobble'
                            }
                        });
                    }
                }
            });
        });

    </script>
    <script>
        // Button - Delete
        $('.btn-delete').click(function(e) {
            e.preventDefault();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': "{{ csrf_token() }}"
                }
            });
            let id = $(this).data('id');
            var url = `{{ url('dashboard/services/${id}') }}`;

            Swal.fire({
                title: 'Deseja remover este registro?',
                text: "Você não poderá reverter isso!",
                icon: 'question',
                showCancelButton: true,
                cancelButtonText: 'Cancelar',
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sim, deletar!'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: url,
                        method: 'DELETE',
                        data: $('#form-table').serialize(),
                        success: function(data) {
                            // Loading service listagem
                            location.href = "{{ url('/dashboard/services') }}";
                        },
                        error: function(xhr) {
                            if (xhr.status === 422) {
                                Swal.fire({
                                    text: xhr.responseJSON,
                                    icon: 'warning',
                                    showClass: {
                                        popup: 'animate_animated animate_wobble'
                                    }
                                });
                            } else {
                                Swal.fire({
                                    text: xhr.responseJSON,
                                    icon: 'error',
                                    showClass: {
                                        popup: 'animate_animated animate_wobble'
                                    }
                                });
                            }
                        }
                    });
                }
            });
        });

    </script>
@endsection

resources/views/backend/services/show.blade.php
@extends('backend.app')

@section('title', 'Serviço - ' . $result->meta_title)

@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ url('/dashboard') }}"><i class="fa fa-home"></i></a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">@yield('title')</li>
    </ol>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12 col-12">
            <div class="box">

                <div class="box-header with-border">
                    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-center">
                        <div>
                            <h4 class="box-title">@yield('title')</h4>
                        </div>
                    </div>
                </div><!-- box-header -->

                <div class="box-body">
                    <!-- conteudo -->

                    @if ($result->image)
                    <p><b>Capa:</b></p>
                        <div class="col-12 col-md-6 border p-3 mb-3">
                            <img src="{{ $result->image }}" alt="{{ $result->meta_title }}" class="img-fluid">
                        </div>
                    @endif

                    <p><b>Conteúdo:</b></p>
                    {!! $result->content !!}

                    <!-- conteudo -->
                </div><!-- box-body -->

                <div class="box-footer flexbox">
                    <div class="text-left flex-grow">
                        <a href="{{ route('services.edit', $result->id) }}"
                            class="btn btn-rounded btn-primary btn-mobile-float" data-toggle="tooltip" data-placement="top"
                            title="Editar Serviço"><i class="fa fa-edit"></i> <span>Editar Serviço</span></a>

                        <a href="{{ route('services.index') }}" class="btn btn-sm btn-rounded btn-info" data-toggle="tooltip"
                            data-placement="top" title="Voltar"><i class="fa fa-angle-left"></i>
                            <span>Voltar</span></a>
                    </div>
                </div><!-- box-footer -->

            </div><!-- box -->
        </div><!-- cols -->
    </div><!-- row -->
@endsection